
// <auto-generated />

// Copyright (c) Blowdart, Inc. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;

namespace Blowdart.UI.Web
{

	public static partial class HtmlExtensions
	{

		#region address

		public static Ui BeginAddress(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("address", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginAddress(this Ui ui, object attr = null)
		{
			return ui.BeginElement("address", attr);
		}

		public static Ui BeginAddress(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("address", attributes);
		}

		public static Ui EndAddress(this Ui ui)
		{
			return ui.EndElement("address");
		}

		public static Ui Address(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("address", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginAddress();
		///		action();
		///		ui.EndAddress();
		///	</code>
		/// </summary>
		public static Ui Address(this Ui ui, Action action)
		{
			return ui.Element("address", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginAddress(attr);
		///		action();
		///		ui.EndAddress();
		///	</code>
		/// </summary>
		public static Ui Address(this Ui ui, object attr, Action action)
		{
			return ui.Element("address", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginAddress();
		///		action(ui);
		///		ui.EndAddress();
		///	</code>
		/// </summary>
		public static Ui Address(this Ui ui, Action<Ui> action)
		{
			return ui.Element("address", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginAddress(attr);
		///		action(ui);
		///		ui.EndAddress();
		///	</code>
		/// </summary>
		public static Ui Address(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("address", attr, action);
		}

		#endregion

		#region article

		public static Ui BeginArticle(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("article", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginArticle(this Ui ui, object attr = null)
		{
			return ui.BeginElement("article", attr);
		}

		public static Ui BeginArticle(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("article", attributes);
		}

		public static Ui EndArticle(this Ui ui)
		{
			return ui.EndElement("article");
		}

		public static Ui Article(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("article", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginArticle();
		///		action();
		///		ui.EndArticle();
		///	</code>
		/// </summary>
		public static Ui Article(this Ui ui, Action action)
		{
			return ui.Element("article", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginArticle(attr);
		///		action();
		///		ui.EndArticle();
		///	</code>
		/// </summary>
		public static Ui Article(this Ui ui, object attr, Action action)
		{
			return ui.Element("article", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginArticle();
		///		action(ui);
		///		ui.EndArticle();
		///	</code>
		/// </summary>
		public static Ui Article(this Ui ui, Action<Ui> action)
		{
			return ui.Element("article", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginArticle(attr);
		///		action(ui);
		///		ui.EndArticle();
		///	</code>
		/// </summary>
		public static Ui Article(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("article", attr, action);
		}

		#endregion

		#region aside

		public static Ui BeginAside(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("aside", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginAside(this Ui ui, object attr = null)
		{
			return ui.BeginElement("aside", attr);
		}

		public static Ui BeginAside(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("aside", attributes);
		}

		public static Ui EndAside(this Ui ui)
		{
			return ui.EndElement("aside");
		}

		public static Ui Aside(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("aside", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginAside();
		///		action();
		///		ui.EndAside();
		///	</code>
		/// </summary>
		public static Ui Aside(this Ui ui, Action action)
		{
			return ui.Element("aside", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginAside(attr);
		///		action();
		///		ui.EndAside();
		///	</code>
		/// </summary>
		public static Ui Aside(this Ui ui, object attr, Action action)
		{
			return ui.Element("aside", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginAside();
		///		action(ui);
		///		ui.EndAside();
		///	</code>
		/// </summary>
		public static Ui Aside(this Ui ui, Action<Ui> action)
		{
			return ui.Element("aside", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginAside(attr);
		///		action(ui);
		///		ui.EndAside();
		///	</code>
		/// </summary>
		public static Ui Aside(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("aside", attr, action);
		}

		#endregion

		#region blockquote

		public static Ui BeginBlockquote(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), string cite = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("blockquote", new { cite, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginBlockquote(this Ui ui, object attr = null)
		{
			return ui.BeginElement("blockquote", attr);
		}

		public static Ui BeginBlockquote(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("blockquote", attributes);
		}

		public static Ui EndBlockquote(this Ui ui)
		{
			return ui.EndElement("blockquote");
		}

		public static Ui Blockquote(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("blockquote", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginBlockquote();
		///		action();
		///		ui.EndBlockquote();
		///	</code>
		/// </summary>
		public static Ui Blockquote(this Ui ui, Action action)
		{
			return ui.Element("blockquote", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginBlockquote(attr);
		///		action();
		///		ui.EndBlockquote();
		///	</code>
		/// </summary>
		public static Ui Blockquote(this Ui ui, object attr, Action action)
		{
			return ui.Element("blockquote", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginBlockquote();
		///		action(ui);
		///		ui.EndBlockquote();
		///	</code>
		/// </summary>
		public static Ui Blockquote(this Ui ui, Action<Ui> action)
		{
			return ui.Element("blockquote", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginBlockquote(attr);
		///		action(ui);
		///		ui.EndBlockquote();
		///	</code>
		/// </summary>
		public static Ui Blockquote(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("blockquote", attr, action);
		}

		#endregion

		#region canvas

		public static Ui BeginCanvas(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), string height = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string), string width = default(string))
		{
			return ui.BeginElement("canvas", new { height, width, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginCanvas(this Ui ui, object attr = null)
		{
			return ui.BeginElement("canvas", attr);
		}

		public static Ui BeginCanvas(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("canvas", attributes);
		}

		public static Ui EndCanvas(this Ui ui)
		{
			return ui.EndElement("canvas");
		}

		public static Ui Canvas(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("canvas", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginCanvas();
		///		action();
		///		ui.EndCanvas();
		///	</code>
		/// </summary>
		public static Ui Canvas(this Ui ui, Action action)
		{
			return ui.Element("canvas", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginCanvas(attr);
		///		action();
		///		ui.EndCanvas();
		///	</code>
		/// </summary>
		public static Ui Canvas(this Ui ui, object attr, Action action)
		{
			return ui.Element("canvas", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginCanvas();
		///		action(ui);
		///		ui.EndCanvas();
		///	</code>
		/// </summary>
		public static Ui Canvas(this Ui ui, Action<Ui> action)
		{
			return ui.Element("canvas", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginCanvas(attr);
		///		action(ui);
		///		ui.EndCanvas();
		///	</code>
		/// </summary>
		public static Ui Canvas(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("canvas", attr, action);
		}

		#endregion

		#region dd

		public static Ui BeginDd(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("dd", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginDd(this Ui ui, object attr = null)
		{
			return ui.BeginElement("dd", attr);
		}

		public static Ui BeginDd(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("dd", attributes);
		}

		public static Ui EndDd(this Ui ui)
		{
			return ui.EndElement("dd");
		}

		public static Ui Dd(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("dd", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDd();
		///		action();
		///		ui.EndDd();
		///	</code>
		/// </summary>
		public static Ui Dd(this Ui ui, Action action)
		{
			return ui.Element("dd", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDd(attr);
		///		action();
		///		ui.EndDd();
		///	</code>
		/// </summary>
		public static Ui Dd(this Ui ui, object attr, Action action)
		{
			return ui.Element("dd", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDd();
		///		action(ui);
		///		ui.EndDd();
		///	</code>
		/// </summary>
		public static Ui Dd(this Ui ui, Action<Ui> action)
		{
			return ui.Element("dd", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDd(attr);
		///		action(ui);
		///		ui.EndDd();
		///	</code>
		/// </summary>
		public static Ui Dd(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("dd", attr, action);
		}

		#endregion

		#region div

		public static Ui BeginDiv(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("div", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginDiv(this Ui ui, object attr = null)
		{
			return ui.BeginElement("div", attr);
		}

		public static Ui BeginDiv(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("div", attributes);
		}

		public static Ui EndDiv(this Ui ui)
		{
			return ui.EndElement("div");
		}

		public static Ui Div(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("div", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDiv();
		///		action();
		///		ui.EndDiv();
		///	</code>
		/// </summary>
		public static Ui Div(this Ui ui, Action action)
		{
			return ui.Element("div", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDiv(attr);
		///		action();
		///		ui.EndDiv();
		///	</code>
		/// </summary>
		public static Ui Div(this Ui ui, object attr, Action action)
		{
			return ui.Element("div", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDiv();
		///		action(ui);
		///		ui.EndDiv();
		///	</code>
		/// </summary>
		public static Ui Div(this Ui ui, Action<Ui> action)
		{
			return ui.Element("div", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDiv(attr);
		///		action(ui);
		///		ui.EndDiv();
		///	</code>
		/// </summary>
		public static Ui Div(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("div", attr, action);
		}

		#endregion

		#region dl

		public static Ui BeginDl(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("dl", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginDl(this Ui ui, object attr = null)
		{
			return ui.BeginElement("dl", attr);
		}

		public static Ui BeginDl(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("dl", attributes);
		}

		public static Ui EndDl(this Ui ui)
		{
			return ui.EndElement("dl");
		}

		public static Ui Dl(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("dl", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDl();
		///		action();
		///		ui.EndDl();
		///	</code>
		/// </summary>
		public static Ui Dl(this Ui ui, Action action)
		{
			return ui.Element("dl", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDl(attr);
		///		action();
		///		ui.EndDl();
		///	</code>
		/// </summary>
		public static Ui Dl(this Ui ui, object attr, Action action)
		{
			return ui.Element("dl", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDl();
		///		action(ui);
		///		ui.EndDl();
		///	</code>
		/// </summary>
		public static Ui Dl(this Ui ui, Action<Ui> action)
		{
			return ui.Element("dl", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDl(attr);
		///		action(ui);
		///		ui.EndDl();
		///	</code>
		/// </summary>
		public static Ui Dl(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("dl", attr, action);
		}

		#endregion

		#region dt

		public static Ui BeginDt(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("dt", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginDt(this Ui ui, object attr = null)
		{
			return ui.BeginElement("dt", attr);
		}

		public static Ui BeginDt(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("dt", attributes);
		}

		public static Ui EndDt(this Ui ui)
		{
			return ui.EndElement("dt");
		}

		public static Ui Dt(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("dt", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDt();
		///		action();
		///		ui.EndDt();
		///	</code>
		/// </summary>
		public static Ui Dt(this Ui ui, Action action)
		{
			return ui.Element("dt", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDt(attr);
		///		action();
		///		ui.EndDt();
		///	</code>
		/// </summary>
		public static Ui Dt(this Ui ui, object attr, Action action)
		{
			return ui.Element("dt", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDt();
		///		action(ui);
		///		ui.EndDt();
		///	</code>
		/// </summary>
		public static Ui Dt(this Ui ui, Action<Ui> action)
		{
			return ui.Element("dt", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginDt(attr);
		///		action(ui);
		///		ui.EndDt();
		///	</code>
		/// </summary>
		public static Ui Dt(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("dt", attr, action);
		}

		#endregion

		#region fieldset

		public static Ui BeginFieldset(this Ui ui, string @class = default(string), string @for = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool disabled = default(bool), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string name = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("fieldset", new { disabled, @for, name, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginFieldset(this Ui ui, object attr = null)
		{
			return ui.BeginElement("fieldset", attr);
		}

		public static Ui BeginFieldset(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("fieldset", attributes);
		}

		public static Ui EndFieldset(this Ui ui)
		{
			return ui.EndElement("fieldset");
		}

		public static Ui Fieldset(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("fieldset", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFieldset();
		///		action();
		///		ui.EndFieldset();
		///	</code>
		/// </summary>
		public static Ui Fieldset(this Ui ui, Action action)
		{
			return ui.Element("fieldset", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFieldset(attr);
		///		action();
		///		ui.EndFieldset();
		///	</code>
		/// </summary>
		public static Ui Fieldset(this Ui ui, object attr, Action action)
		{
			return ui.Element("fieldset", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFieldset();
		///		action(ui);
		///		ui.EndFieldset();
		///	</code>
		/// </summary>
		public static Ui Fieldset(this Ui ui, Action<Ui> action)
		{
			return ui.Element("fieldset", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFieldset(attr);
		///		action(ui);
		///		ui.EndFieldset();
		///	</code>
		/// </summary>
		public static Ui Fieldset(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("fieldset", attr, action);
		}

		#endregion

		#region figcaption

		public static Ui BeginFigcaption(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("figcaption", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginFigcaption(this Ui ui, object attr = null)
		{
			return ui.BeginElement("figcaption", attr);
		}

		public static Ui BeginFigcaption(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("figcaption", attributes);
		}

		public static Ui EndFigcaption(this Ui ui)
		{
			return ui.EndElement("figcaption");
		}

		public static Ui Figcaption(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("figcaption", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFigcaption();
		///		action();
		///		ui.EndFigcaption();
		///	</code>
		/// </summary>
		public static Ui Figcaption(this Ui ui, Action action)
		{
			return ui.Element("figcaption", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFigcaption(attr);
		///		action();
		///		ui.EndFigcaption();
		///	</code>
		/// </summary>
		public static Ui Figcaption(this Ui ui, object attr, Action action)
		{
			return ui.Element("figcaption", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFigcaption();
		///		action(ui);
		///		ui.EndFigcaption();
		///	</code>
		/// </summary>
		public static Ui Figcaption(this Ui ui, Action<Ui> action)
		{
			return ui.Element("figcaption", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFigcaption(attr);
		///		action(ui);
		///		ui.EndFigcaption();
		///	</code>
		/// </summary>
		public static Ui Figcaption(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("figcaption", attr, action);
		}

		#endregion

		#region figure

		public static Ui BeginFigure(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("figure", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginFigure(this Ui ui, object attr = null)
		{
			return ui.BeginElement("figure", attr);
		}

		public static Ui BeginFigure(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("figure", attributes);
		}

		public static Ui EndFigure(this Ui ui)
		{
			return ui.EndElement("figure");
		}

		public static Ui Figure(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("figure", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFigure();
		///		action();
		///		ui.EndFigure();
		///	</code>
		/// </summary>
		public static Ui Figure(this Ui ui, Action action)
		{
			return ui.Element("figure", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFigure(attr);
		///		action();
		///		ui.EndFigure();
		///	</code>
		/// </summary>
		public static Ui Figure(this Ui ui, object attr, Action action)
		{
			return ui.Element("figure", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFigure();
		///		action(ui);
		///		ui.EndFigure();
		///	</code>
		/// </summary>
		public static Ui Figure(this Ui ui, Action<Ui> action)
		{
			return ui.Element("figure", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFigure(attr);
		///		action(ui);
		///		ui.EndFigure();
		///	</code>
		/// </summary>
		public static Ui Figure(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("figure", attr, action);
		}

		#endregion

		#region footer

		public static Ui BeginFooter(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("footer", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginFooter(this Ui ui, object attr = null)
		{
			return ui.BeginElement("footer", attr);
		}

		public static Ui BeginFooter(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("footer", attributes);
		}

		public static Ui EndFooter(this Ui ui)
		{
			return ui.EndElement("footer");
		}

		public static Ui Footer(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("footer", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFooter();
		///		action();
		///		ui.EndFooter();
		///	</code>
		/// </summary>
		public static Ui Footer(this Ui ui, Action action)
		{
			return ui.Element("footer", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFooter(attr);
		///		action();
		///		ui.EndFooter();
		///	</code>
		/// </summary>
		public static Ui Footer(this Ui ui, object attr, Action action)
		{
			return ui.Element("footer", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFooter();
		///		action(ui);
		///		ui.EndFooter();
		///	</code>
		/// </summary>
		public static Ui Footer(this Ui ui, Action<Ui> action)
		{
			return ui.Element("footer", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginFooter(attr);
		///		action(ui);
		///		ui.EndFooter();
		///	</code>
		/// </summary>
		public static Ui Footer(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("footer", attr, action);
		}

		#endregion

		#region form

		public static Ui BeginForm(this Ui ui, string @class = default(string), string accept = default(string), string acceptCharset = default(string), string accesskey = default(string), string action = default(string), string autocapitalize = default(string), string autocomplete = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), string enctype = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string method = default(string), string name = default(string), string novalidate = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string target = default(string), string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("form", new { accept, acceptCharset, action, autocomplete, enctype, method, name, novalidate, target, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginForm(this Ui ui, object attr = null)
		{
			return ui.BeginElement("form", attr);
		}

		public static Ui BeginForm(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("form", attributes);
		}

		public static Ui EndForm(this Ui ui)
		{
			return ui.EndElement("form");
		}

		public static Ui Form(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("form", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginForm();
		///		action();
		///		ui.EndForm();
		///	</code>
		/// </summary>
		public static Ui Form(this Ui ui, Action action)
		{
			return ui.Element("form", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginForm(attr);
		///		action();
		///		ui.EndForm();
		///	</code>
		/// </summary>
		public static Ui Form(this Ui ui, object attr, Action action)
		{
			return ui.Element("form", attr, action);
		}

		public static Ui Form(this Ui ui, Action<FormAttributes> action)
		{
			return ui.Element("form", new { }, x =>
			{
				var attributes = new FormAttributes();
				attributes.method = "post";
				action(attributes);
			});
		}

		public struct FormAttributes
		{
			public string method;
		}
		

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginForm();
		///		action(ui);
		///		ui.EndForm();
		///	</code>
		/// </summary>
		public static Ui Form(this Ui ui, Action<Ui> action)
		{
			return ui.Element("form", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginForm(attr);
		///		action(ui);
		///		ui.EndForm();
		///	</code>
		/// </summary>
		public static Ui Form(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("form", attr, action);
		}

		#endregion

		#region h1

		public static Ui BeginH1(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("h1", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginH1(this Ui ui, object attr = null)
		{
			return ui.BeginElement("h1", attr);
		}

		public static Ui BeginH1(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("h1", attributes);
		}

		public static Ui EndH1(this Ui ui)
		{
			return ui.EndElement("h1");
		}

		public static Ui H1(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("h1", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH1();
		///		action();
		///		ui.EndH1();
		///	</code>
		/// </summary>
		public static Ui H1(this Ui ui, Action action)
		{
			return ui.Element("h1", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH1(attr);
		///		action();
		///		ui.EndH1();
		///	</code>
		/// </summary>
		public static Ui H1(this Ui ui, object attr, Action action)
		{
			return ui.Element("h1", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH1();
		///		action(ui);
		///		ui.EndH1();
		///	</code>
		/// </summary>
		public static Ui H1(this Ui ui, Action<Ui> action)
		{
			return ui.Element("h1", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH1(attr);
		///		action(ui);
		///		ui.EndH1();
		///	</code>
		/// </summary>
		public static Ui H1(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("h1", attr, action);
		}

		#endregion

		#region h2

		public static Ui BeginH2(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("h2", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginH2(this Ui ui, object attr = null)
		{
			return ui.BeginElement("h2", attr);
		}

		public static Ui BeginH2(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("h2", attributes);
		}

		public static Ui EndH2(this Ui ui)
		{
			return ui.EndElement("h2");
		}

		public static Ui H2(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("h2", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH2();
		///		action();
		///		ui.EndH2();
		///	</code>
		/// </summary>
		public static Ui H2(this Ui ui, Action action)
		{
			return ui.Element("h2", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH2(attr);
		///		action();
		///		ui.EndH2();
		///	</code>
		/// </summary>
		public static Ui H2(this Ui ui, object attr, Action action)
		{
			return ui.Element("h2", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH2();
		///		action(ui);
		///		ui.EndH2();
		///	</code>
		/// </summary>
		public static Ui H2(this Ui ui, Action<Ui> action)
		{
			return ui.Element("h2", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH2(attr);
		///		action(ui);
		///		ui.EndH2();
		///	</code>
		/// </summary>
		public static Ui H2(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("h2", attr, action);
		}

		#endregion

		#region h3

		public static Ui BeginH3(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("h3", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginH3(this Ui ui, object attr = null)
		{
			return ui.BeginElement("h3", attr);
		}

		public static Ui BeginH3(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("h3", attributes);
		}

		public static Ui EndH3(this Ui ui)
		{
			return ui.EndElement("h3");
		}

		public static Ui H3(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("h3", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH3();
		///		action();
		///		ui.EndH3();
		///	</code>
		/// </summary>
		public static Ui H3(this Ui ui, Action action)
		{
			return ui.Element("h3", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH3(attr);
		///		action();
		///		ui.EndH3();
		///	</code>
		/// </summary>
		public static Ui H3(this Ui ui, object attr, Action action)
		{
			return ui.Element("h3", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH3();
		///		action(ui);
		///		ui.EndH3();
		///	</code>
		/// </summary>
		public static Ui H3(this Ui ui, Action<Ui> action)
		{
			return ui.Element("h3", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH3(attr);
		///		action(ui);
		///		ui.EndH3();
		///	</code>
		/// </summary>
		public static Ui H3(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("h3", attr, action);
		}

		#endregion

		#region h4

		public static Ui BeginH4(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("h4", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginH4(this Ui ui, object attr = null)
		{
			return ui.BeginElement("h4", attr);
		}

		public static Ui BeginH4(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("h4", attributes);
		}

		public static Ui EndH4(this Ui ui)
		{
			return ui.EndElement("h4");
		}

		public static Ui H4(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("h4", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH4();
		///		action();
		///		ui.EndH4();
		///	</code>
		/// </summary>
		public static Ui H4(this Ui ui, Action action)
		{
			return ui.Element("h4", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH4(attr);
		///		action();
		///		ui.EndH4();
		///	</code>
		/// </summary>
		public static Ui H4(this Ui ui, object attr, Action action)
		{
			return ui.Element("h4", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH4();
		///		action(ui);
		///		ui.EndH4();
		///	</code>
		/// </summary>
		public static Ui H4(this Ui ui, Action<Ui> action)
		{
			return ui.Element("h4", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH4(attr);
		///		action(ui);
		///		ui.EndH4();
		///	</code>
		/// </summary>
		public static Ui H4(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("h4", attr, action);
		}

		#endregion

		#region h5

		public static Ui BeginH5(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("h5", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginH5(this Ui ui, object attr = null)
		{
			return ui.BeginElement("h5", attr);
		}

		public static Ui BeginH5(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("h5", attributes);
		}

		public static Ui EndH5(this Ui ui)
		{
			return ui.EndElement("h5");
		}

		public static Ui H5(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("h5", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH5();
		///		action();
		///		ui.EndH5();
		///	</code>
		/// </summary>
		public static Ui H5(this Ui ui, Action action)
		{
			return ui.Element("h5", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH5(attr);
		///		action();
		///		ui.EndH5();
		///	</code>
		/// </summary>
		public static Ui H5(this Ui ui, object attr, Action action)
		{
			return ui.Element("h5", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH5();
		///		action(ui);
		///		ui.EndH5();
		///	</code>
		/// </summary>
		public static Ui H5(this Ui ui, Action<Ui> action)
		{
			return ui.Element("h5", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH5(attr);
		///		action(ui);
		///		ui.EndH5();
		///	</code>
		/// </summary>
		public static Ui H5(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("h5", attr, action);
		}

		#endregion

		#region h6

		public static Ui BeginH6(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("h6", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginH6(this Ui ui, object attr = null)
		{
			return ui.BeginElement("h6", attr);
		}

		public static Ui BeginH6(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("h6", attributes);
		}

		public static Ui EndH6(this Ui ui)
		{
			return ui.EndElement("h6");
		}

		public static Ui H6(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("h6", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH6();
		///		action();
		///		ui.EndH6();
		///	</code>
		/// </summary>
		public static Ui H6(this Ui ui, Action action)
		{
			return ui.Element("h6", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH6(attr);
		///		action();
		///		ui.EndH6();
		///	</code>
		/// </summary>
		public static Ui H6(this Ui ui, object attr, Action action)
		{
			return ui.Element("h6", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH6();
		///		action(ui);
		///		ui.EndH6();
		///	</code>
		/// </summary>
		public static Ui H6(this Ui ui, Action<Ui> action)
		{
			return ui.Element("h6", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginH6(attr);
		///		action(ui);
		///		ui.EndH6();
		///	</code>
		/// </summary>
		public static Ui H6(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("h6", attr, action);
		}

		#endregion

		#region header

		public static Ui BeginHeader(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("header", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginHeader(this Ui ui, object attr = null)
		{
			return ui.BeginElement("header", attr);
		}

		public static Ui BeginHeader(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("header", attributes);
		}

		public static Ui EndHeader(this Ui ui)
		{
			return ui.EndElement("header");
		}

		public static Ui Header(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("header", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginHeader();
		///		action();
		///		ui.EndHeader();
		///	</code>
		/// </summary>
		public static Ui Header(this Ui ui, Action action)
		{
			return ui.Element("header", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginHeader(attr);
		///		action();
		///		ui.EndHeader();
		///	</code>
		/// </summary>
		public static Ui Header(this Ui ui, object attr, Action action)
		{
			return ui.Element("header", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginHeader();
		///		action(ui);
		///		ui.EndHeader();
		///	</code>
		/// </summary>
		public static Ui Header(this Ui ui, Action<Ui> action)
		{
			return ui.Element("header", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginHeader(attr);
		///		action(ui);
		///		ui.EndHeader();
		///	</code>
		/// </summary>
		public static Ui Header(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("header", attr, action);
		}

		#endregion

		#region hr

		public static Ui BeginHr(this Ui ui, string @class = default(string), string accesskey = default(string), string align = default(string), string autocapitalize = default(string), string color = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("hr", new { align, color, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginHr(this Ui ui, object attr = null)
		{
			return ui.BeginElement("hr", attr);
		}

		public static Ui BeginHr(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("hr", attributes);
		}

		public static Ui EndHr(this Ui ui)
		{
			return ui.EndElement("hr");
		}

		public static Ui Hr(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("hr", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginHr();
		///		action();
		///		ui.EndHr();
		///	</code>
		/// </summary>
		public static Ui Hr(this Ui ui, Action action)
		{
			return ui.Element("hr", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginHr(attr);
		///		action();
		///		ui.EndHr();
		///	</code>
		/// </summary>
		public static Ui Hr(this Ui ui, object attr, Action action)
		{
			return ui.Element("hr", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginHr();
		///		action(ui);
		///		ui.EndHr();
		///	</code>
		/// </summary>
		public static Ui Hr(this Ui ui, Action<Ui> action)
		{
			return ui.Element("hr", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginHr(attr);
		///		action(ui);
		///		ui.EndHr();
		///	</code>
		/// </summary>
		public static Ui Hr(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("hr", attr, action);
		}

		#endregion

		#region li

		public static Ui BeginLi(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string), string value = default(string))
		{
			return ui.BeginElement("li", new { value, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginLi(this Ui ui, object attr = null)
		{
			return ui.BeginElement("li", attr);
		}

		public static Ui BeginLi(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("li", attributes);
		}

		public static Ui EndLi(this Ui ui)
		{
			return ui.EndElement("li");
		}

		public static Ui Li(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("li", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginLi();
		///		action();
		///		ui.EndLi();
		///	</code>
		/// </summary>
		public static Ui Li(this Ui ui, Action action)
		{
			return ui.Element("li", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginLi(attr);
		///		action();
		///		ui.EndLi();
		///	</code>
		/// </summary>
		public static Ui Li(this Ui ui, object attr, Action action)
		{
			return ui.Element("li", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginLi();
		///		action(ui);
		///		ui.EndLi();
		///	</code>
		/// </summary>
		public static Ui Li(this Ui ui, Action<Ui> action)
		{
			return ui.Element("li", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginLi(attr);
		///		action(ui);
		///		ui.EndLi();
		///	</code>
		/// </summary>
		public static Ui Li(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("li", attr, action);
		}

		#endregion

		#region main

		public static Ui BeginMain(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("main", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginMain(this Ui ui, object attr = null)
		{
			return ui.BeginElement("main", attr);
		}

		public static Ui BeginMain(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("main", attributes);
		}

		public static Ui EndMain(this Ui ui)
		{
			return ui.EndElement("main");
		}

		public static Ui Main(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("main", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginMain();
		///		action();
		///		ui.EndMain();
		///	</code>
		/// </summary>
		public static Ui Main(this Ui ui, Action action)
		{
			return ui.Element("main", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginMain(attr);
		///		action();
		///		ui.EndMain();
		///	</code>
		/// </summary>
		public static Ui Main(this Ui ui, object attr, Action action)
		{
			return ui.Element("main", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginMain();
		///		action(ui);
		///		ui.EndMain();
		///	</code>
		/// </summary>
		public static Ui Main(this Ui ui, Action<Ui> action)
		{
			return ui.Element("main", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginMain(attr);
		///		action(ui);
		///		ui.EndMain();
		///	</code>
		/// </summary>
		public static Ui Main(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("main", attr, action);
		}

		#endregion

		#region nav

		public static Ui BeginNav(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("nav", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginNav(this Ui ui, object attr = null)
		{
			return ui.BeginElement("nav", attr);
		}

		public static Ui BeginNav(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("nav", attributes);
		}

		public static Ui EndNav(this Ui ui)
		{
			return ui.EndElement("nav");
		}

		public static Ui Nav(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("nav", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginNav();
		///		action();
		///		ui.EndNav();
		///	</code>
		/// </summary>
		public static Ui Nav(this Ui ui, Action action)
		{
			return ui.Element("nav", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginNav(attr);
		///		action();
		///		ui.EndNav();
		///	</code>
		/// </summary>
		public static Ui Nav(this Ui ui, object attr, Action action)
		{
			return ui.Element("nav", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginNav();
		///		action(ui);
		///		ui.EndNav();
		///	</code>
		/// </summary>
		public static Ui Nav(this Ui ui, Action<Ui> action)
		{
			return ui.Element("nav", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginNav(attr);
		///		action(ui);
		///		ui.EndNav();
		///	</code>
		/// </summary>
		public static Ui Nav(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("nav", attr, action);
		}

		#endregion

		#region noscript

		public static Ui BeginNoscript(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("noscript", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginNoscript(this Ui ui, object attr = null)
		{
			return ui.BeginElement("noscript", attr);
		}

		public static Ui BeginNoscript(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("noscript", attributes);
		}

		public static Ui EndNoscript(this Ui ui)
		{
			return ui.EndElement("noscript");
		}

		public static Ui Noscript(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("noscript", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginNoscript();
		///		action();
		///		ui.EndNoscript();
		///	</code>
		/// </summary>
		public static Ui Noscript(this Ui ui, Action action)
		{
			return ui.Element("noscript", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginNoscript(attr);
		///		action();
		///		ui.EndNoscript();
		///	</code>
		/// </summary>
		public static Ui Noscript(this Ui ui, object attr, Action action)
		{
			return ui.Element("noscript", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginNoscript();
		///		action(ui);
		///		ui.EndNoscript();
		///	</code>
		/// </summary>
		public static Ui Noscript(this Ui ui, Action<Ui> action)
		{
			return ui.Element("noscript", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginNoscript(attr);
		///		action(ui);
		///		ui.EndNoscript();
		///	</code>
		/// </summary>
		public static Ui Noscript(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("noscript", attr, action);
		}

		#endregion

		#region ol

		public static Ui BeginOl(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), bool reversed = default(bool), string slot = default(string), string spellcheck = default(string), string start = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("ol", new { reversed, start, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginOl(this Ui ui, object attr = null)
		{
			return ui.BeginElement("ol", attr);
		}

		public static Ui BeginOl(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("ol", attributes);
		}

		public static Ui EndOl(this Ui ui)
		{
			return ui.EndElement("ol");
		}

		public static Ui Ol(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("ol", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginOl();
		///		action();
		///		ui.EndOl();
		///	</code>
		/// </summary>
		public static Ui Ol(this Ui ui, Action action)
		{
			return ui.Element("ol", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginOl(attr);
		///		action();
		///		ui.EndOl();
		///	</code>
		/// </summary>
		public static Ui Ol(this Ui ui, object attr, Action action)
		{
			return ui.Element("ol", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginOl();
		///		action(ui);
		///		ui.EndOl();
		///	</code>
		/// </summary>
		public static Ui Ol(this Ui ui, Action<Ui> action)
		{
			return ui.Element("ol", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginOl(attr);
		///		action(ui);
		///		ui.EndOl();
		///	</code>
		/// </summary>
		public static Ui Ol(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("ol", attr, action);
		}

		#endregion

		#region p

		public static Ui BeginP(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("p", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginP(this Ui ui, object attr = null)
		{
			return ui.BeginElement("p", attr);
		}

		public static Ui BeginP(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("p", attributes);
		}

		public static Ui EndP(this Ui ui)
		{
			return ui.EndElement("p");
		}

		public static Ui P(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("p", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginP();
		///		action();
		///		ui.EndP();
		///	</code>
		/// </summary>
		public static Ui P(this Ui ui, Action action)
		{
			return ui.Element("p", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginP(attr);
		///		action();
		///		ui.EndP();
		///	</code>
		/// </summary>
		public static Ui P(this Ui ui, object attr, Action action)
		{
			return ui.Element("p", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginP();
		///		action(ui);
		///		ui.EndP();
		///	</code>
		/// </summary>
		public static Ui P(this Ui ui, Action<Ui> action)
		{
			return ui.Element("p", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginP(attr);
		///		action(ui);
		///		ui.EndP();
		///	</code>
		/// </summary>
		public static Ui P(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("p", attr, action);
		}

		#endregion

		#region pre

		public static Ui BeginPre(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("pre", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginPre(this Ui ui, object attr = null)
		{
			return ui.BeginElement("pre", attr);
		}

		public static Ui BeginPre(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("pre", attributes);
		}

		public static Ui EndPre(this Ui ui)
		{
			return ui.EndElement("pre");
		}

		public static Ui Pre(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("pre", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginPre();
		///		action();
		///		ui.EndPre();
		///	</code>
		/// </summary>
		public static Ui Pre(this Ui ui, Action action)
		{
			return ui.Element("pre", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginPre(attr);
		///		action();
		///		ui.EndPre();
		///	</code>
		/// </summary>
		public static Ui Pre(this Ui ui, object attr, Action action)
		{
			return ui.Element("pre", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginPre();
		///		action(ui);
		///		ui.EndPre();
		///	</code>
		/// </summary>
		public static Ui Pre(this Ui ui, Action<Ui> action)
		{
			return ui.Element("pre", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginPre(attr);
		///		action(ui);
		///		ui.EndPre();
		///	</code>
		/// </summary>
		public static Ui Pre(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("pre", attr, action);
		}

		#endregion

		#region section

		public static Ui BeginSection(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("section", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginSection(this Ui ui, object attr = null)
		{
			return ui.BeginElement("section", attr);
		}

		public static Ui BeginSection(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("section", attributes);
		}

		public static Ui EndSection(this Ui ui)
		{
			return ui.EndElement("section");
		}

		public static Ui Section(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("section", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginSection();
		///		action();
		///		ui.EndSection();
		///	</code>
		/// </summary>
		public static Ui Section(this Ui ui, Action action)
		{
			return ui.Element("section", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginSection(attr);
		///		action();
		///		ui.EndSection();
		///	</code>
		/// </summary>
		public static Ui Section(this Ui ui, object attr, Action action)
		{
			return ui.Element("section", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginSection();
		///		action(ui);
		///		ui.EndSection();
		///	</code>
		/// </summary>
		public static Ui Section(this Ui ui, Action<Ui> action)
		{
			return ui.Element("section", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginSection(attr);
		///		action(ui);
		///		ui.EndSection();
		///	</code>
		/// </summary>
		public static Ui Section(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("section", attr, action);
		}

		#endregion

		#region table

		public static Ui BeginTable(this Ui ui, string @class = default(string), string accesskey = default(string), string align = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), string summary = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("table", new { align, summary, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginTable(this Ui ui, object attr = null)
		{
			return ui.BeginElement("table", attr);
		}

		public static Ui BeginTable(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("table", attributes);
		}

		public static Ui EndTable(this Ui ui)
		{
			return ui.EndElement("table");
		}

		public static Ui Table(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("table", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginTable();
		///		action();
		///		ui.EndTable();
		///	</code>
		/// </summary>
		public static Ui Table(this Ui ui, Action action)
		{
			return ui.Element("table", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginTable(attr);
		///		action();
		///		ui.EndTable();
		///	</code>
		/// </summary>
		public static Ui Table(this Ui ui, object attr, Action action)
		{
			return ui.Element("table", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginTable();
		///		action(ui);
		///		ui.EndTable();
		///	</code>
		/// </summary>
		public static Ui Table(this Ui ui, Action<Ui> action)
		{
			return ui.Element("table", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginTable(attr);
		///		action(ui);
		///		ui.EndTable();
		///	</code>
		/// </summary>
		public static Ui Table(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("table", attr, action);
		}

		#endregion

		#region tfoot

		public static Ui BeginTfoot(this Ui ui, string @class = default(string), string accesskey = default(string), string align = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("tfoot", new { align, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginTfoot(this Ui ui, object attr = null)
		{
			return ui.BeginElement("tfoot", attr);
		}

		public static Ui BeginTfoot(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("tfoot", attributes);
		}

		public static Ui EndTfoot(this Ui ui)
		{
			return ui.EndElement("tfoot");
		}

		public static Ui Tfoot(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("tfoot", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginTfoot();
		///		action();
		///		ui.EndTfoot();
		///	</code>
		/// </summary>
		public static Ui Tfoot(this Ui ui, Action action)
		{
			return ui.Element("tfoot", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginTfoot(attr);
		///		action();
		///		ui.EndTfoot();
		///	</code>
		/// </summary>
		public static Ui Tfoot(this Ui ui, object attr, Action action)
		{
			return ui.Element("tfoot", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginTfoot();
		///		action(ui);
		///		ui.EndTfoot();
		///	</code>
		/// </summary>
		public static Ui Tfoot(this Ui ui, Action<Ui> action)
		{
			return ui.Element("tfoot", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginTfoot(attr);
		///		action(ui);
		///		ui.EndTfoot();
		///	</code>
		/// </summary>
		public static Ui Tfoot(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("tfoot", attr, action);
		}

		#endregion

		#region ul

		public static Ui BeginUl(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), bool contenteditable = default(bool), string contextmenu = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), string slot = default(string), string spellcheck = default(string), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string))
		{
			return ui.BeginElement("ul", new { contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginUl(this Ui ui, object attr = null)
		{
			return ui.BeginElement("ul", attr);
		}

		public static Ui BeginUl(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("ul", attributes);
		}

		public static Ui EndUl(this Ui ui)
		{
			return ui.EndElement("ul");
		}

		public static Ui Ul(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("ul", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginUl();
		///		action();
		///		ui.EndUl();
		///	</code>
		/// </summary>
		public static Ui Ul(this Ui ui, Action action)
		{
			return ui.Element("ul", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginUl(attr);
		///		action();
		///		ui.EndUl();
		///	</code>
		/// </summary>
		public static Ui Ul(this Ui ui, object attr, Action action)
		{
			return ui.Element("ul", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginUl();
		///		action(ui);
		///		ui.EndUl();
		///	</code>
		/// </summary>
		public static Ui Ul(this Ui ui, Action<Ui> action)
		{
			return ui.Element("ul", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginUl(attr);
		///		action(ui);
		///		ui.EndUl();
		///	</code>
		/// </summary>
		public static Ui Ul(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("ul", attr, action);
		}

		#endregion

		#region video

		public static Ui BeginVideo(this Ui ui, string @class = default(string), string accesskey = default(string), string autocapitalize = default(string), string autoplay = default(string), string buffered = default(string), bool contenteditable = default(bool), string contextmenu = default(string), bool controls = default(bool), string crossorigin = default(string), string dir = default(string), bool draggable = default(bool), string dropzone = default(string), string height = default(string), bool hidden = default(bool), string id = default(string), string itemprop = default(string), string lang = default(string), bool loop = default(bool), bool muted = default(bool), string poster = default(string), string preload = default(string), string slot = default(string), string spellcheck = default(string), Uri src = default(Uri), string style = default(string), int? tabindex = null, string title = default(string), string translate = default(string), string width = default(string))
		{
			return ui.BeginElement("video", new { controls, loop, muted, autoplay, buffered, crossorigin, height, poster, preload, src, width, contenteditable, draggable, accesskey, autocapitalize, @class, contextmenu, dir, dropzone, hidden, id, itemprop, lang, slot, spellcheck, style, tabindex, title, translate });
		}

		public static Ui BeginVideo(this Ui ui, object attr = null)
		{
			return ui.BeginElement("video", attr);
		}

		public static Ui BeginVideo(this Ui ui, params object[] attributes)
		{
			return ui.BeginElement("video", attributes);
		}

		public static Ui EndVideo(this Ui ui)
		{
			return ui.EndElement("video");
		}

		public static Ui Video(this Ui ui, string innerText, object attr = null)
		{
			return ui.Element("video", innerText, attr);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginVideo();
		///		action();
		///		ui.EndVideo();
		///	</code>
		/// </summary>
		public static Ui Video(this Ui ui, Action action)
		{
			return ui.Element("video", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginVideo(attr);
		///		action();
		///		ui.EndVideo();
		///	</code>
		/// </summary>
		public static Ui Video(this Ui ui, object attr, Action action)
		{
			return ui.Element("video", attr, action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginVideo();
		///		action(ui);
		///		ui.EndVideo();
		///	</code>
		/// </summary>
		public static Ui Video(this Ui ui, Action<Ui> action)
		{
			return ui.Element("video", action);
		}

		/// <summary> This call is equivalent to: 
		///	<code>
		///		ui.BeginVideo(attr);
		///		action(ui);
		///		ui.EndVideo();
		///	</code>
		/// </summary>
		public static Ui Video(this Ui ui, object attr, Action<Ui> action)
		{
			return ui.Element("video", attr, action);
		}

		#endregion
	}
}

