trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

## Use .NET Core 3.0
- task: UseDotNet@2
  displayName: Use .NET Core 3.0.x
  inputs:
    packageType: 'sdk'
    version: '3.0.x'


## NuGet Restore
- task: NuGetCommand@2
  displayName: Restore Packages
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    arguments: '--configuration Release'

## Build Platform
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/HQ.Platform.sln'
