#region LICENSE

// Unless explicitly acquired and licensed from Licensor under another
// license, the contents of this file are subject to the Reciprocal Public
// License ("RPL") Version 1.5, or subsequent versions as allowed by the RPL,
// and You may not copy or use this file in either source code or executable
// form, except in compliance with the terms and conditions of the RPL.
// 
// All software distributed under the RPL is provided strictly on an "AS
// IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND
// LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
// LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific
// language governing rights and limitations under the RPL.

#endregion

namespace HQ.UI.Web.SemanticUi
{
	public enum ArrowIcons
	{
		AngleDoubleDown,
		AngleDoubleLeft,
		AngleDoubleRight,
		AngleDoubleUp,
		AngleDown,
		AngleLeft,
		AngleRight,
		AngleUp,
		ArrowAlternateCircleDown,
		ArrowAlternateCircleDownOutline,
		ArrowAlternateCircleLeft,
		ArrowAlternateCircleLeftOutline,
		ArrowAlternateCircleRight,
		ArrowAlternateCircleRightOutline,
		ArrowAlternateCircleUp,
		ArrowAlternateCircleUpOutline,
		ArrowCircleDown,
		ArrowCircleLeft,
		ArrowCircleRight,
		ArrowCircleUp,
		ArrowDown,
		ArrowLeft,
		ArrowRight,
		ArrowUp,
		ArrowsAlternate,
		ArrowsAlternateHorizontal,
		ArrowsAlternateVertical,
		CaretDown,
		CaretLeft,
		CaretRight,
		CaretSquareDown,
		CaretSquareDownOutline,
		CaretSquareLeft,
		CaretSquareLeftOutline,
		CaretSquareRight,
		CaretSquareRightOutline,
		CaretSquareUp,
		CaretSquareUpOutline,
		CaretUp,
		CartArrowDown,
		ChartLine,
		ChevronCircleDown,
		ChevronCircleLeft,
		ChevronCircleRight,
		ChevronCircleUp,
		ChevronDown,
		ChevronLeft,
		ChevronRight,
		ChevronUp,
		CloudDownload,
		CloudUpload,
		Download,
		ExchangeAlternate,
		ExpandArrowsAlternate,
		ExternalAlternate,
		ExternalSquareAlternate,
		HandPointDown,
		HandPointDownOutline,
		HandPointLeft,
		HandPointLeftOutline,
		HandPointRight,
		HandPointRightOutline,
		HandPointUp,
		HandPointUpOutline,
		HandPointer,
		HandPointerOutline,
		History,
		LevelDownAlternate,
		LevelUpAlternate,
		LocationArrow,
		LongArrowAlternateDown,
		LongArrowAlternateLeft,
		LongArrowAlternateRight,
		LongArrowAlternateUp,
		MousePointer,
		Play,
		Random,
		Recycle,
		Redo,
		RedoAlternate,
		Reply,
		ReplyAll,
		Retweet,
		Share,
		ShareSquare,
		ShareSquareOutline,
		SignInAlternate,
		SignOutAlternate,
		Sort,
		SortAlphabetDown,
		SortAlphabetUp,
		SortAmountDown,
		SortAmountUp,
		SortDown,
		SortNumericDown,
		SortNumericUp,
		SortUp,
		Sync,
		SyncAlternate,
		TextHeight,
		TextWidth,
		Undo,
		UndoAlternate,
		Upload
	}
}