// Copyright (c) Daniel Crenna & Contributors. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

namespace Lime.Web.SemanticUi
{
	public enum AudioVideoIcons
	{
		AudioDescription,
		Backward,
		Circle,
		CircleOutline,
		ClosedCaptioning,
		ClosedCaptioningOutline,
		Compress,
		Eject,
		Expand,
		ExpandArrowsAlternate,
		FastBackward,
		FastForward,
		FileAudio,
		FileAudioOutline,
		FileVideo,
		FileVideoOutline,
		Film,
		Forward,
		Headphones,
		Microphone,
		MicrophoneSlash,
		Music,
		Pause,
		PauseCircle,
		PauseCircleOutline,
		PhoneVolume,
		Play,
		PlayCircle,
		PlayCircleOutline,
		Podcast,
		Random,
		Redo,
		RedoAlternate,
		Rss,
		RssSquare,
		StepBackward,
		StepForward,
		Stop,
		StopCircle,
		StopCircleOutline,
		Sync,
		SyncAlternate,
		Undo,
		UndoAlternate,
		Video,
		VolumeDown,
		VolumeOff,
		VolumeUp
	}
}